general:
    type: 'BNS'
    num_waveforms: 50000
    waveform_duration: 64 #desired duration of time-domain waveform
    sample_rate: 2048
    right_pad: 1.0 #coalescence point of signal [s] from right edge of window
    f_min: 20
    f_max: 1024
    f_ref: 50
    ifos: ['H1', 'L1']
    batch_size: 350
    seed: 0

waveform:
    mass_1:
        func: transforms.Triangular
        args: [1.0, 2.5, 2.5]
    mass_2:
        func: torch.distributions.Uniform
        args: [1.0, 'mass_1']
    s1z:
        func: ml4gw.distributions.DeltaFunction
        args: [0]
    s2z:
        func: ml4gw.distributions.DeltaFunction
        args: [0]
    distance:
        func: ml4gw.distributions.PowerLaw
        args: [100, 1000, 2]
    phic:
        func: ml4gw.distributions.DeltaFunction
        args: [0]
    inclination:
        func: ml4gw.distributions.Sine

whiten:
    fftlength: 2
    average: median
    overlap: null
    psd_length: 64
    fduration: 2

snr_reweighting: 
        func: ml4gw.distributions.PowerLaw
        args: [8,100,-3] 
