general:
    type: BBH
    num_waveforms: 500
    waveform_duration: 8 #desired duration of time-domain waveform
    sample_rate: 2048
    right_pad: 0.5 #coalescence point of signal [s] from right edge of window
    f_min: 20
    f_max: 1024
    f_ref: 20
    ifos: ['H1','L1']

waveform:
    chirp_mass:
        func: ml4gw.distributions.PowerLaw
        args: [10, 100, -2.35]
    mass_ratio:
        func: torch.distributions.Uniform
        args: [0.125, 0.999]
    chi1:
        func: torch.distributions.Uniform
        args: [-0.999, 0.999]
    chi2:
        func: torch.distributions.Uniform
        args: [-0.999, 0.999]
    distance:
        func: ml4gw.distributions.PowerLaw
        args: [100, 1000, 2]
    phic:
        func: ml4gw.distributions.DeltaFunction
        args: [0]
    inclination:
        func: ml4gw.distributions.Sine

whiten:
    fftlength: 2
    average: median
    overlap: null
    psd_length: 16
    fduration: 2

snr_reweighting:
        func: ml4gw.distributions.PowerLaw
        args: [12,100,-3]
